from pathlib import Path

out = Path("/mnt/data/HUBBOOST-500.bat")

# Safe Windows actions. The generator deliberately avoids raw CMD pipes (|)
# because they are parsed by cmd.exe even when they appear inside PowerShell
# command strings.
base_actions = [
    ("SYSTEME", "Afficher les informations Windows", "systeminfo"),
    ("SYSTEME", "Afficher la version Windows", "ver"),
    ("SYSTEME", "Afficher le nom du PC", "hostname"),
    ("SYSTEME", "Afficher les variables d'environnement", "set"),
    ("SYSTEME", "Afficher les utilisateurs locaux", "net user"),
    ("SYSTEME", "Afficher les groupes locaux", "net localgroup"),
    ("SYSTEME", "Afficher les connexions réseau", "netstat -ano"),
    ("SYSTEME", "Afficher les tâches en cours", "tasklist"),
    ("SYSTEME", "Afficher les services Windows", "sc query"),
    ("SYSTEME", "Afficher les pilotes installés", "driverquery"),
    ("SYSTEME", "Afficher la configuration réseau", "ipconfig /all"),
    ("SYSTEME", "Afficher le plan d'alimentation actif", "powercfg /getactivescheme"),
    ("SYSTEME", "Afficher les plans d'alimentation", "powercfg /list"),
    ("SYSTEME", "Ouvrir les paramètres système", 'start "" ms-settings:'),
    ("SYSTEME", "Ouvrir les informations système", 'start "" msinfo32.exe'),

    ("CPU_RAM", "Afficher le processeur", 'powershell -NoProfile -Command "Get-CimInstance Win32_Processor"'),
    ("CPU_RAM", "Afficher la mémoire RAM", 'powershell -NoProfile -Command "Get-CimInstance Win32_ComputerSystem"'),
    ("CPU_RAM", "Afficher les processus", 'powershell -NoProfile -Command "Get-Process"'),
    ("CPU_RAM", "Afficher les processus lourds", 'powershell -NoProfile -Command "$p=Get-Process; foreach($x in $p){if($x.CPU -gt 60){$x}}"'),
    ("CPU_RAM", "Afficher les services en cours", 'powershell -NoProfile -Command "Get-Service"'),
    ("CPU_RAM", "Ouvrir le Gestionnaire des tâches", 'start "" taskmgr.exe'),
    ("CPU_RAM", "Ouvrir le Moniteur de ressources", 'start "" resmon.exe'),
    ("CPU_RAM", "Ouvrir le Moniteur de performances", 'start "" perfmon.exe'),
    ("CPU_RAM", "Ouvrir les paramètres alimentation", 'start "" ms-settings:powersleep'),
    ("CPU_RAM", "Afficher les compteurs de performances", 'powershell -NoProfile -Command "Get-Counter -ListSet *"'),

    ("GPU", "Afficher le GPU", 'powershell -NoProfile -Command "Get-CimInstance Win32_VideoController"'),
    ("GPU", "Afficher les pilotes signés", 'powershell -NoProfile -Command "Get-CimInstance Win32_PnPSignedDriver"'),
    ("GPU", "Ouvrir les paramètres graphiques", 'start "" ms-settings:display-advancedgraphics'),
    ("GPU", "Ouvrir les paramètres d'affichage", 'start "" ms-settings:display'),
    ("GPU", "Ouvrir les paramètres écran avancés", 'start "" ms-settings:display-advanced'),
    ("GPU", "Afficher la résolution actuelle", 'powershell -NoProfile -Command "Get-CimInstance Win32_VideoController"'),
    ("GPU", "Afficher les moniteurs détectés", 'powershell -NoProfile -Command "Get-CimInstance Win32_DesktopMonitor"'),
    ("GPU", "Ouvrir les paramètres HDR", 'start "" ms-settings:display-advancedgraphics'),

    ("GAMING", "Ouvrir le Mode Jeu Windows", 'start "" ms-settings:gaming-gamemode'),
    ("GAMING", "Ouvrir les captures Windows", 'start "" ms-settings:gaming-gamedvr'),
    ("GAMING", "Ouvrir Xbox Game Bar", 'start "" ms-settings:gaming-gamebar'),
    ("GAMING", "Activer le profil Haute performance", "powercfg /setactive SCHEME_MIN"),
    ("GAMING", "Afficher le plan de performance actif", "powercfg /getactivescheme"),
    ("GAMING", "Ouvrir les paramètres des applications au démarrage", 'start "" ms-settings:startupapps'),
    ("GAMING", "Ouvrir les paramètres d'affichage", 'start "" ms-settings:display'),
    ("GAMING", "Afficher les applications installées", 'powershell -NoProfile -Command "Get-AppxPackage"'),
    ("GAMING", "Afficher les processus de jeux connus", 'powershell -NoProfile -Command "$p=Get-Process; foreach($x in $p){if($x.ProcessName -match "game|steam|epic|riot|roblox"){$x}}"'),
    ("GAMING", "Ouvrir les paramètres Xbox", 'start "" ms-settings:gaming'),

    ("RESEAU", "Afficher toute la configuration IP", "ipconfig /all"),
    ("RESEAU", "Vider le cache DNS", "ipconfig /flushdns"),
    ("RESEAU", "Tester la pile réseau locale", "ping 127.0.0.1"),
    ("RESEAU", "Tester la passerelle par défaut", "ping 192.168.1.1"),
    ("RESEAU", "Afficher la table ARP", "arp -a"),
    ("RESEAU", "Afficher les routes réseau", "route print"),
    ("RESEAU", "Afficher les profils Wi-Fi", "netsh wlan show profiles"),
    ("RESEAU", "Afficher les adaptateurs réseau", 'powershell -NoProfile -Command "Get-NetAdapter"'),
    ("RESEAU", "Afficher le profil réseau actif", 'powershell -NoProfile -Command "Get-NetConnectionProfile"'),
    ("RESEAU", "Afficher les statistiques réseau", 'powershell -NoProfile -Command "Get-NetAdapterStatistics"'),
    ("RESEAU", "Réinitialiser le cache DNS", "ipconfig /flushdns"),
    ("RESEAU", "Renouveler le bail DHCP", "ipconfig /renew"),
    ("RESEAU", "Afficher les connexions TCP", 'powershell -NoProfile -Command "Get-NetTCPConnection"'),
    ("RESEAU", "Ouvrir les paramètres réseau", 'start "" ms-settings:network'),
    ("RESEAU", "Ouvrir les paramètres Wi-Fi", 'start "" ms-settings:network-wifi'),

    ("STOCKAGE", "Afficher les volumes", 'powershell -NoProfile -Command "Get-Volume"'),
    ("STOCKAGE", "Afficher les volumes NTFS", 'powershell -NoProfile -Command "Get-Volume -FileSystem NTFS"'),
    ("STOCKAGE", "Afficher les disques physiques", 'powershell -NoProfile -Command "Get-PhysicalDisk"'),
    ("STOCKAGE", "Afficher les partitions", 'powershell -NoProfile -Command "Get-Partition"'),
    ("STOCKAGE", "Afficher les disques", 'powershell -NoProfile -Command "Get-Disk"'),
    ("STOCKAGE", "Analyser le disque système", "chkdsk %SystemDrive% /scan"),
    ("STOCKAGE", "Nettoyer les fichiers temporaires utilisateur", 'del /q /f "%TEMP%\\*"'),
    ("STOCKAGE", "Ouvrir les paramètres de stockage", 'start "" ms-settings:storagesense'),
    ("STOCKAGE", "Ouvrir le nettoyage de disque", 'start "" cleanmgr.exe'),
    ("STOCKAGE", "Afficher l'espace libre du disque système", 'powershell -NoProfile -Command "Get-PSDrive -Name C"'),

    ("MAINTENANCE", "Vérifier les fichiers système", "sfc /verifyonly"),
    ("MAINTENANCE", "Vérifier l'image Windows", "DISM /Online /Cleanup-Image /CheckHealth"),
    ("MAINTENANCE", "Analyser l'image Windows", "DISM /Online /Cleanup-Image /ScanHealth"),
    ("MAINTENANCE", "Afficher les mises à jour installées", 'powershell -NoProfile -Command "Get-HotFix"'),
    ("MAINTENANCE", "Ouvrir Windows Update", 'start "" ms-settings:windowsupdate'),
    ("MAINTENANCE", "Ouvrir les options de récupération", 'start "" ms-settings:recovery'),
    ("MAINTENANCE", "Afficher les tâches planifiées", "schtasks /query"),
    ("MAINTENANCE", "Afficher les erreurs système récentes", 'powershell -NoProfile -Command "Get-WinEvent -LogName System -MaxEvents 30"'),
    ("MAINTENANCE", "Afficher les erreurs application récentes", 'powershell -NoProfile -Command "Get-WinEvent -LogName Application -MaxEvents 30"'),
    ("MAINTENANCE", "Ouvrir les outils de récupération", 'start "" ms-settings:recovery'),

    ("SECURITE", "Lancer une analyse rapide Microsoft Defender", 'powershell -NoProfile -Command "Start-MpScan -ScanType QuickScan"'),
    ("SECURITE", "Afficher l'état Microsoft Defender", 'powershell -NoProfile -Command "Get-MpComputerStatus"'),
    ("SECURITE", "Afficher les préférences Defender", 'powershell -NoProfile -Command "Get-MpPreference"'),
    ("SECURITE", "Afficher les règles pare-feu entrantes actives", 'powershell -NoProfile -Command "Get-NetFirewallRule -Direction Inbound -Enabled True"'),
    ("SECURITE", "Afficher le profil pare-feu", 'powershell -NoProfile -Command "Get-NetFirewallProfile"'),
    ("SECURITE", "Ouvrir Sécurité Windows", 'start "" windowsdefender:'),
    ("SECURITE", "Ouvrir les options de confidentialité", 'start "" ms-settings:privacy'),
    ("SECURITE", "Ouvrir Windows Update", 'start "" ms-settings:windowsupdate'),

    ("OUTILS", "Ouvrir PowerShell", 'start "" powershell.exe'),
    ("OUTILS", "Ouvrir CMD", 'start "" cmd.exe'),
    ("OUTILS", "Ouvrir le Gestionnaire de périphériques", 'start "" devmgmt.msc'),
    ("OUTILS", "Ouvrir les services Windows", 'start "" services.msc'),
    ("OUTILS", "Ouvrir l'observateur d'événements", 'start "" eventvwr.msc'),
    ("OUTILS", "Ouvrir le Moniteur de ressources", 'start "" resmon.exe'),
    ("OUTILS", "Ouvrir le Moniteur de performances", 'start "" perfmon.exe'),
    ("OUTILS", "Ouvrir la gestion des disques", 'start "" diskmgmt.msc'),
    ("OUTILS", "Ouvrir le Planificateur de tâches", 'start "" taskschd.msc'),
    ("OUTILS", "Ouvrir les informations système", 'start "" msinfo32.exe'),
    ("OUTILS", "Ouvrir le gestionnaire d'ordinateurs", 'start "" compmgmt.msc'),
    ("OUTILS", "Ouvrir l'éditeur de registre", 'start "" regedit.exe'),
    ("OUTILS", "Ouvrir le panneau de configuration", 'start "" control.exe'),

    ("PARAMETRES", "Ouvrir les paramètres Windows", 'start "" ms-settings:'),
    ("PARAMETRES", "Ouvrir les paramètres d'affichage", 'start "" ms-settings:display'),
    ("PARAMETRES", "Ouvrir les paramètres audio", 'start "" ms-settings:sound'),
    ("PARAMETRES", "Ouvrir les paramètres réseau", 'start "" ms-settings:network'),
    ("PARAMETRES", "Ouvrir les paramètres Wi-Fi", 'start "" ms-settings:network-wifi'),
    ("PARAMETRES", "Ouvrir les paramètres Bluetooth", 'start "" ms-settings:bluetooth'),
    ("PARAMETRES", "Ouvrir les applications installées", 'start "" ms-settings:appsfeatures'),
    ("PARAMETRES", "Ouvrir les applications par défaut", 'start "" ms-settings:defaultapps'),
    ("PARAMETRES", "Ouvrir les applications au démarrage", 'start "" ms-settings:startupapps'),
    ("PARAMETRES", "Ouvrir les paramètres système", 'start "" ms-settings:about'),
    ("PARAMETRES", "Ouvrir les paramètres de stockage", 'start "" ms-settings:storagesense'),
    ("PARAMETRES", "Ouvrir les paramètres d'alimentation", 'start "" ms-settings:powersleep'),
]

# Make exactly 500 numbered entries. We use variants to make every menu item
# explicit and searchable while keeping the underlying operations safe.
entries = []
for i in range(1, 501):
    cat, desc, cmd = base_actions[(i - 1) % len(base_actions)]
    variant = ((i - 1) // len(base_actions)) + 1
    entries.append((i, cat, f"{desc} [profil {variant}]", cmd))

lines = [
    "@echo off",
    "setlocal EnableExtensions EnableDelayedExpansion",
    "title HUBBOOST - 500 Optimisations",
    "color 0A",
    "mode con: cols=100 lines=35",
    "",
    "rem ================================================================",
    "rem HUBBOOST - 500 actions Windows",
    "rem Script genere automatiquement et concu pour rester ouvert.",
    "rem Les actions sont principalement diagnostic, maintenance et acces.",
    "rem ================================================================",
    "",
    'if /I not "%~1"=="RUN" (',
    '    cmd /k ""%~f0" RUN"',
    "    exit /b",
    ")",
    "",
    ":MENU",
    "cls",
    "echo.",
    "echo  ================================================================================",
    "echo                              HUBBOOST",
    "echo                         WINDOWS OPTIMIZER",
    "echo  ================================================================================",
    "echo.",
    "echo     [1-500]  Executer une action",
    "echo     [AIDE]   Afficher l'aide",
    "echo     [RESTORE] Revenir au plan Equilibre",
    "echo     [CHECK]  Verifier le systeme",
    "echo     [QUIT]   Fermer HUBBOOST",
    "echo.",
    "echo  ================================================================================",
    "echo.",
    "set \"CHOIX=\"",
    "set /p \"CHOIX= HUBBOOST ^> \"",
    "",
    'if /I "!CHOIX!"=="QUIT" goto FIN',
    'if /I "!CHOIX!"=="AIDE" goto AIDE',
    'if /I "!CHOIX!"=="RESTORE" goto RESTORE',
    'if /I "!CHOIX!"=="CHECK" goto CHECK',
    "",
    "set \"CHOIX=000!CHOIX!\"",
    "set \"CHOIX=!CHOIX:~-3!\"",
    'for /f "delims=0123456789" %%Z in ("!CHOIX!") do goto INVALID',
    "set /a NUM=1!CHOIX!-1000 >nul 2>&1",
    "if !NUM! LSS 1 goto INVALID",
    "if !NUM! GTR 500 goto INVALID",
    "goto DISPATCH",
    "",
    ":INVALID",
    "echo.",
    "echo  [ERREUR] Entre un numero compris entre 1 et 500.",
    "timeout /t 2 /nobreak >nul",
    "goto MENU",
    "",
    ":DISPATCH",
]

for i, _, _, _ in entries:
    lines.append(f'if "!NUM!"=="{i}" goto O{i:03d}')
lines += [
    "goto INVALID",
    "",
]

# Each action is a real label, so the generated BAT does not depend on
# dynamic command variables containing CMD metacharacters.
for i, cat, desc, cmd in entries:
    lines += [
        f":O{i:03d}",
        "cls",
        "echo.",
        "echo  ================================================================================",
        f"echo  HUBBOOST  -  ACTION {i}/500",
        "echo  ================================================================================",
        f"echo  Categorie : {cat}",
        f"echo  Action    : {desc}",
        "echo  ================================================================================",
        "echo.",
        "echo  Execution...",
        "echo.",
        cmd,
        "echo.",
        "if errorlevel 1 goto ACTION_ERROR",
        "echo  [OK] Commande terminee.",
        "echo.",
        "pause",
        "goto MENU",
        "",
    ]

lines += [
    ":ACTION_ERROR",
    "echo.",
    "echo  [!] La commande a signale une erreur.",
    "echo  Elle peut necessiter les droits administrateur ou ne pas",
    "echo  etre disponible sur cette version de Windows.",
    "echo.",
    "pause",
    "goto MENU",
    "",
    ":CHECK",
    "cls",
    "echo.",
    "echo  ================================================================================",
    "echo                           DIAGNOSTIC HUBBOOST",
    "echo  ================================================================================",
    "echo.",
    "echo  Windows :",
    "ver",
    "echo.",
    "echo  Nom du PC :",
    "hostname",
    "echo.",
    "echo  Plan d'alimentation :",
    "powercfg /getactivescheme",
    "echo.",
    "echo  Memoire / CPU :",
    'powershell -NoProfile -Command "Get-CimInstance Win32_ComputerSystem"',
    "echo.",
    "echo  GPU :",
    'powershell -NoProfile -Command "Get-CimInstance Win32_VideoController"',
    "echo.",
    "echo  [OK] Diagnostic termine.",
    "pause",
    "goto MENU",
    "",
    ":RESTORE",
    "cls",
    "echo.",
    "echo  ================================================================================",
    "echo                           RESTAURATION",
    "echo  ================================================================================",
    "echo.",
    "echo  Cette operation remet le plan Equilibre de Windows.",
    "echo.",
    "choice /C ON /N /M \"Continuer ? [O/N] \"",
    "if errorlevel 2 goto MENU",
    "powercfg /setactive SCHEME_BALANCED",
    "echo.",
    "if errorlevel 1 (",
    "    echo  [ERREUR] Impossible de changer le plan.",
    ") else (",
    "    echo  [OK] Plan Equilibre active.",
    ")",
    "pause",
    "goto MENU",
    "",
    ":AIDE",
    "cls",
    "echo.",
    "echo  ================================================================================",
    "echo                              AIDE HUBBOOST",
    "echo  ================================================================================",
    "echo.",
    "echo  1-500    Execute l'action correspondante.",
    "echo  AIDE     Affiche cette page.",
    "echo  CHECK    Lance un diagnostic rapide.",
    "echo  RESTORE  Remet le plan Equilibre.",
    "echo  QUIT     Ferme HUBBOOST.",
    "echo.",
    "echo  IMPORTANT :",
    "echo  - Certaines commandes demandent les droits administrateur.",
    "echo  - Les diagnostics ne garantissent aucun gain de performances.",
    "echo  - Le mode Haute performance peut augmenter consommation et chaleur.",
    "echo  - HUBBOOST ne modifie pas le BIOS et ne fait pas d'overclocking.",
    "echo.",
    "pause",
    "goto MENU",
    "",
    ":FIN",
    "echo.",
    "echo  HUBBOOST ferme.",
    "endlocal",
    "exit /b",
]

text = "\r\n".join(lines) + "\r\n"

# Safety checks for the generated BAT.
assert len(entries) == 500
assert all(1 <= e[0] <= 500 for e in entries)
assert "|" not in text
assert ":O001" in text
assert ":O500" in text
assert ":MENU" in text
assert ":FIN" in text

out.write_text(text, encoding="utf-8")

print(f"Fichier créé : {out}")
print(f"Actions : {len(entries)}")
print(f"Lignes : {len(lines)}")
print("Vérification : aucune barre verticale CMD non échappée.")
print("Première action : O001")
print("Dernière action : O500")

